currency-client-starter.enabled=${CURRENCY_CLIENT_STARTER_ENABLED}
currency-client-starter.api-key=${CURRENCY_CLIENT_STARTER_API_KEY}
currency-client-starter.base-url=${CURRENCY_CLIENT_STARTER_BASE_URL}

CURRENCY_CLIENT_STARTER_ENABLED = true
CURRENCY_CLIENT_STARTER_API_KEY = f6a112f643875616aeafec4d
CURRENCY_CLIENT_STARTER_BASE_URL = https://v6.exchangerate-api.com