currency-client-starter.enabled=${CURRENCY_CLIENT_STARTER_ENABLED}
currency-client-starter.api-key=${CURRENCY_CLIENT_STARTER_API_KEY}
currency-client-starter.base-url=${CURRENCY_CLIENT_STARTER_BASE_URL}

#Retry
currency-client-starter.retry.enabled=${CURRENCY_CLIENT_STARTER_RETRY_ENABLED}
currency-client-starter.retry.max-attempts=${CURRENCY_CLIENT_STARTER_RETRY_MAX_ATTEMPTS}
currency-client-starter.retry.backoff=${CURRENCY_CLIENT_STARTER_RETRY_BACKOFF}

#Health
currency-client-starter.health=${CURRENCY_CLIENT_STARTER_HEALTH_ENABLED}

CURRENCY_CLIENT_STARTER_ENABLED = true
CURRENCY_CLIENT_STARTER_API_KEY = f6a112f643875616aeafec4d
CURRENCY_CLIENT_STARTER_BASE_URL = https://v6.exchangerate-api.com

CURRENCY_CLIENT_STARTER_RETRY_ENABLED = true
CURRENCY_CLIENT_STARTER_RETRY_MAX_ATTEMPTS = 3
CURRENCY_CLIENT_STARTER_RETRY_BACKOFF = 1000

CURRENCY_CLIENT_STARTER_HEALTH_ENABLED = true
